"use strict";
exports.__esModule = true;
var camioneta_1 = require("./camioneta");
var autoDeportivo_1 = require("./autoDeportivo");
var autoCiudad_1 = require("./autoCiudad");
var camioneta = new camioneta_1.Camioneta('Toyota', false);
console.log('Esta es la CAMIONETA, al crearla ', camioneta);
camioneta.acelerar();
camioneta.setMarca('Ford');
camioneta.setColor();
camioneta.prender();
camioneta.setCaja();
console.log('Esta es la CAMIONETA, al modificarla ', camioneta);
var autoDeportivo = new autoDeportivo_1.AutoDeportivo('Hyundai');
console.log('Este es la AUTO DEPORTIVO, al crearlo ', autoDeportivo);
autoDeportivo.acelerar();
autoDeportivo.setMarca('Mercedes');
autoDeportivo.setColor();
autoDeportivo.prender();
autoDeportivo.setDescapotableCaja();
console.log('Este es la AUTO DEPORTIVO, al modificarlo ', autoDeportivo);
var autoCiudad = new autoCiudad_1.AutoCiudad('Ford', 'manual');
console.log('Este es la AUTO CIDUDAD, al crearlo ', autoCiudad);
autoCiudad.acelerar();
autoCiudad.setMarca('Mercedes');
autoCiudad.setColor();
autoCiudad.prender();
autoCiudad.setTipoCaja('automatica');
console.log('Este es la AUTO CIDUDAD, al modificarlo ', autoCiudad);
